sonar.organization=johngech
sonar.projectKey=debo-ethiopia
sonar.projectName=Debo Ethiopia Web Project
sonar.sources=src
sonar.exclusions=**/node_modules/**, **/*.test.tsx, **/dist/**, **/build/**, tailwind.config.js, postcss.config.js
sonar.typescript.tsconfigPath=tsconfig.json
sonar.scm.disabled=false
sonar.qualitygate.wait=true